config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => "users/registrations"}
  root 'home#index'

  get 'home/auth'
  get 'home/project'
  get 'home/subjects_csv'
  get 'home/hla_csv'
  get 'home/kir_csv'
  get 'home/c19_symptoms_csv'
  get 'home/comorbidities_csv'
  get 'home/hospitalizations_csv'
  get 'home/lab_tests_csv'
  get 'home/risk_factors_csv'
  get 'home/treatments_csv'
  get 'home/stats_csv'
  get 'home/age_data'
  get 'home/sex_data'
  get 'home/contributor_table_data'
  get 'home/allele_freq_data'
  get 'home/download_manual'
  get 'home/new_account_approval'
  post 'home/new_account_approval_handler'
  get 'project/index/:project_id', to: 'project#index', as: 'project_index'
  get 'upload/index'
  get 'upload/get_report'
  patch 'upload/import_data'
  patch 'upload/store'
  get 'upload/download_template'
  get 'upload/download_dictionary'
  get 'datatables/subjects'
  get 'datatables/c19_symptoms'
  get 'datatables/hla'
  get 'datatables/kir'
  get 'datatables/comorbidity'
  get 'datatables/hospitalization'
  post 'datatables/labtest'
  get 'datatables/riskfactor'
  get 'datatables/treatment'
  post 'query/data'
  post 'query/import_hla'
  post 'query/hibag_preflight'
  post 'query/user_key'
  post 'home/approve_users'
  get '*unmatched', to: 'error#error_404', via: :all, as: 'error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/upload_helper.rb
module UploadHelper
    # creates a master list of valid column headers for each table
    def valid_colnames
        Subject.column_names.reject{ |cn| ["created_at", "updated_at", "id", "hlac19_id"].include? cn }.concat(
        C19Symptom.column_names.reject{ |cn| ["created_at", "updated_at", "id", "subject_id"].include? cn }).concat(
        Comorbidity.column_names.reject{ |cn| ["created_at", "updated_at", "id", "subject_id"].include? cn }).concat(
        Hla.column_names.reject{ |cn| ["created_at", "updated_at", "id", "subject_id"].include? cn }).concat(
        Hospitalization.column_names.reject{ |cn| ["created_at", "updated_at", "id", "subject_id"].include? cn }).concat(
        LabTest.column_names.reject{ |cn| ["created_at", "updated_at", "id", "subject_id"].include? cn }).concat(
        RiskFactor.column_names.reject{ |cn| ["created_at", "updated_at", "id", "subject_id"].include? cn }).concat( 
        Treatment.column_names.reject{ |cn| ["created_at", "updated_at", "id", "subject_id"].include? cn }).concat(
        Kir.column_names.reject{ |cn| ["created_at", "updated_at", "id", "subject_id"].include? cn})
    end
    # this checks the headers in an uploaded CSV file against the schema table headers and returns headers not found in the schema
    def check_headers(csvHeaders)
        bad_headers = csvHeaders.reject{ |h| valid_colnames.include? h }
        headers_ok = bad_headers.size > 0 ? false : true
        { :form_ok => headers_ok, :bad_headers => bad_headers }
    end
    # method to turn NA values - common substitute for null/nil - to a ActiveRecord/mysql-friendly null value
    def coerce_na_values_to_nil(hsh)
        hsh.each{ |k,v| !v.nil? && (["na","n/a","-"].include? v.downcase) ? hsh[k] = nil : next }
    end
    # this separates the one long CSV row into smaller hashes aligned to each table's variables.
    def parse_row(row)
        {
            :subject => parse_subject_fields(row),
            :c19_symptom => parse_c19symptom_fields(row),
            :comorbidity => parse_comorbidity_fields(row),
            :hla => parse_hla_fields(row),
            :hospitalization => parse_hospitalization_fields(row),
            :labtest => parse_labtest_fields(row),
            :riskfactor => parse_riskfactor_fields(row),
            :treatment => parse_treatment_fields(row),
            :kir => parse_kir_fields(row)
        }
    end
    def parse_row_longitudinal(row)
        {
            :subject => parse_subject_fields(row),
            :c19_symptom => parse_c19symptom_fields(row),
            :comorbidity => nil,
            :hla => nil,
            :hospitalization => parse_hospitalization_fields(row),
            :labtest => parse_labtest_fields(row),
            :riskfactor => nil,
            :treatment => parse_treatment_fields(row),
            :kir => parse_kir_fields(row)
        }
    end
    # these methods extract values from the csv row that match variable names in the table the methods are named after.
    # if there are no values for a particular table's variables, nil is returned.
    def parse_subject_fields(row)
        sub_params = row.select{ |k,v| Subject.column_names.include? k } 
        sub_params = Hash[sub_params.collect{ |arr| [arr[0], arr[1]] } ] 
        sub_params = coerce_na_values_to_nil(sub_params)
        sub_params.values.reject{ |v| v == nil }.count > 0 ? sub_params : nil
    end

    def parse_c19symptom_fields(row)
        c19_params = row.select{ |k,v| C19Symptom.column_names.include? k } 
        c19_params = Hash[c19_params.collect{ |arr| [arr[0], arr[1]] } ] 
        c19_params = coerce_na_values_to_nil(c19_params)
        c19_params.values.reject{ |v| v == nil }.count > 0 ? c19_params : nil
    end

    def parse_comorbidity_fields(row)
        com_params = row.select{ |k,v| Comorbidity.column_names.include? k } 
        com_params = Hash[com_params.collect{ |arr| [arr[0], arr[1]] } ] 
        com_params = coerce_na_values_to_nil(com_params)
        com_params.values.reject{ |v| v == nil }.count > 0 ? com_params : nil
    end

    def parse_hla_fields(row)
        hla_params = row.select{ |k,v| Hla.column_names.include? k } 
        hla_params = Hash[hla_params.collect{ |arr| [arr[0], arr[1]] } ] 
        hla_params = coerce_na_values_to_nil(hla_params)
        hla_params.values.reject{ |v| v == nil }.count > 0 ? hla_params : nil
    end

    def parse_hospitalization_fields(row)
        hzn_params = row.select{ |k,v| Hospitalization.column_names.include? k } 
        hzn_params = Hash[hzn_params.collect{ |arr| [arr[0], arr[1]] } ] 
        hzn_params = coerce_na_values_to_nil(hzn_params)
        hzn_params.values.reject{ |v| v == nil }.count > 0 ? hzn_params : nil
    end

    def parse_labtest_fields(row)
        lab_params = row.select{ |k,v| LabTest.column_names.include? k } 
        lab_params = Hash[lab_params.collect{ |arr| [arr[0], arr[1]] } ] 
        lab_params = coerce_na_values_to_nil(lab_params)
        lab_params.values.reject{ |v| v == nil }.count > 0 ? lab_params : nil
    end

    def parse_riskfactor_fields(row)
        rkf_params = row.select{ |k,v| RiskFactor.column_names.include? k } 
        rkf_params = Hash[rkf_params.collect{ |arr| [arr[0], arr[1]] } ] 
        rkf_params = coerce_na_values_to_nil(rkf_params)
        rkf_params.values.reject{ |v| v == nil }.count > 0 ? rkf_params : nil
    end

    def parse_treatment_fields(row)
        tmt_params = row.select{ |k,v| Treatment.column_names.include? k } 
        tmt_params = Hash[tmt_params.collect{ |arr| [arr[0], arr[1]] } ] 
        tmt_params = coerce_na_values_to_nil(tmt_params)
        tmt_params.values.reject{ |v| v == nil }.count > 0 ? tmt_params : nil
    end

    def parse_kir_fields(row)
        kir_params = row.select{ |k,v| Kir.column_names.include? k } 
        kir_params = Hash[kir_params.collect{ |arr| [arr[0], arr[1]] } ] 
        kir_params = coerce_na_values_to_nil(kir_params)
        kir_params.values.reject{ |v| v == nil }.count > 0 ? kir_params : nil
    end
    # this builds and saves subject-related models 
    def build_relations(sub, data)
        unless !data[:c19_symptom]
            @c19 = C19Symptom.new(data[:c19_symptom])
            @c19[:subject_id] = sub.id
            @c19.save
        end
        unless !data[:comorbidity]
            #sub.build_comorbidity(data[:comorbidity]).save
            @com = Comorbidity.new(data[:comorbidity])
            @com[:subject_id] = sub.id
            @com.save
        end
        unless !data[:hla]
            #sub.build_hla(data[:hla]).save
            @hla = Hla.new(data[:hla])
            @hla[:subject_id] = sub.id
            @hla.save
        end
        unless !data[:hospitalization]
            #sub.build_hospitalization(data[:hospitalization]).save
            @hos = Hospitalization.new(data[:hospitalization])
            @hos[:subject_id] = sub.id
            @hos.save
        end
        unless !data[:labtest]
            #sub.build_lab_test(data[:labtest]).save
            @lab = LabTest.new(data[:labtest])
            @lab[:subject_id] = sub.id
            @lab.save
        end
        unless !data[:riskfactor]
            #sub.build_risk_factor(data[:risk_factor]).save
            @rf = RiskFactor.new(data[:risk_factor])
            @rf[:subject_id] = sub.id
            @rf.save
        end
        unless !data[:treatment]
            #sub.build_treatment(data[:treatment]).save
            @tmt = Treatment.new(data[:treatment])
            @tmt[:subject_id] = sub.id
            @tmt.save
        end
        unless !data[:kir]
            #sub.build_hla(data[:hla]).save
            @kir = Kir.new(data[:kir])
            @kir[:subject_id] = sub.id
            @kir.save
        end
    end

end

app/views/upload/index.html.erb
<div class="container" style="margin-top:20px;">
    <div class="row justify-content-md-left">
        <div class="col-md-auto">
            <h4><%= current_user.email %><br>File Upload History</h4>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <%=link_to "Download Data Template File", upload_download_template_path, target: :blank, :class => "btn btn-primary", :style => "margin-right:50px;" %>
        <%=link_to "Download Data Dictionary", upload_download_dictionary_path, target: :blank, :class => "btn btn-primary" %>
    </div>
    <hr>
    <div class="row justify-content-md-center"><h6>All uploaded data is embargoed by default. See the database manual for information and instructions on data sharing.</h6></div>
    <hr>
    <div class="row justify-content-md-center" style="margin-top:30px">
        <div class="col-md-6" style="padding-top:10px;">
            <h5>Previous Uploads</h5>
            <ul style="list-style-type:none;padding:0;">
                <% current_user.uploads.each do |u|%>
                    <li><%= u.created_at.strftime("%Y-%m-%d") %>&nbsp;&nbsp;<%= u.filename.to_json %>
                        <% if UploadRecord.find_by(active_storage_attachment_id:u.id).nil? %>
                            <%= "" %>
                        <% else %> 
                            <%= link_to "Download Report", upload_get_report_path(:upload_report_id => UploadRecord.find_by(active_storage_attachment_id:u.id).id, format:'text')  %>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div class="col-md-6" style="padding-top:10px;">  
            
            <%= form_with(model: @user, url: "/upload/import_data", action: 'post') do |f|%>
                <h5>Upload File</h5>
                <hr>
                <div class="row ">
                    <h6>1. Choose which of your data sets or projects to add the data</h6>
                    <%= f.select :project_name, options_for_select(@projects.pluck(:name)), {}, {class: "form-control" } %>
                </div>
                <hr>
                <div class="row"> 
                    <h6>2. Are you uploading new subjects, or adding longitudinal data for existing subjects?</h6>
                    <div class="form-check">  
                        <%= f.radio_button :upload_type, "new_subject", :class => "form-check-input", :checked => true %>
                        <%= f.label :upload_type, "Upload new subjects", :value => "new_subject" %><br>
                        <%= f.radio_button :upload_type, "long_data", :class => "form-check-input" %>
                        <%= f.label :upload_type, "Add new longitudinal data to existing subjects", :value => "long_data" %><br>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <h6>3. Choose a file from your computer</h6>
                    <%= f.file_field :attachment, multiple: false, direct_upload: true %><br /><br />
                </div>
                <br>
                <div class="row">
                    <%= f.check_box :irb_sharing_approved, :id => "irb_checkbox", :checked => false, :style => "margin-right:10px;" %>
                    <%= f.label :irb_sharing_approved, "I am authorized by my IRB/ethics committee to share the data I am uploading.", :style => "font-size:10pt;font-weight:bold;" %>
                </div>
                <%= f.submit "Upload File", :class => "btn btn-primary", :id => "file_upload_submit", :disabled => false, :data => {:toggle => "modal", :target => "#spinnerModal"} %>
            <% end %>
        </div>
    </div>
    <%= render 'upload/partials/spinner'%>
</div>