config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => "users/registrations"}
  root 'home#index'

  get 'home/auth'
  get 'home/project'
  get 'home/subjects_csv'
  get 'home/hla_csv'
  get 'home/kir_csv'
  get 'home/c19_symptoms_csv'
  get 'home/comorbidities_csv'
  get 'home/hospitalizations_csv'
  get 'home/lab_tests_csv'
  get 'home/risk_factors_csv'
  get 'home/treatments_csv'
  get 'home/stats_csv'
  get 'home/age_data'
  get 'home/sex_data'
  get 'home/contributor_table_data'
  get 'home/allele_freq_data'
  get 'home/download_manual'
  get 'home/new_account_approval'
  post 'home/new_account_approval_handler'
  get 'project/index/:project_id', to: 'project#index', as: 'project_index'
  get 'upload/index'
  get 'upload/get_report'
  patch 'upload/import_data'
  patch 'upload/store'
  get 'upload/download_template'
  get 'upload/download_dictionary'
  get 'datatables/subjects'
  get 'datatables/c19_symptoms'
  get 'datatables/hla'
  get 'datatables/kir'
  get 'datatables/comorbidity'
  get 'datatables/hospitalization'
  post 'datatables/labtest'
  get 'datatables/riskfactor'
  get 'datatables/treatment'
  post 'query/data'
  post 'query/import_hla'
  post 'query/hibag_preflight'
  post 'query/user_key'
  post 'home/approve_users'
  get '*unmatched', to: 'error#error_404', via: :all, as: 'error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :subjects, :dependent => :delete_all
  has_paper_trail
  require 'csv'

  validates :name, uniqueness: { scope: :user_id, message: "A user's projects may not have identical names" }

  after_destroy :wipe_name_from_users_project_list


  def wipe_name_from_users_project_list
    new_list = self.user.project_name - [self.name]
    self.user.update(project_name:new_list)
  end
  # The method for generating these csv files is: 
  # 1) Generate a list of the table's column names, stripping out unneeded columns such as id, created_at, etc.
  # 2) For tables that are related to (aka "owned by") the Subjects table, also generate a list of subject identifiers and concatenate the two column header lists
  # 3) Pull the information for the combined column header list and write to a csv file
  def get_subjects
    CSV.generate do |csv|
        sub_col_heads = Subject.column_names.reject{ |cn| ["id", "project_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        subjects_ids = self.subjects.pluck(:id)
        hlas = Hla.where(subject_id:subjects_ids)
        csv << sub_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*sub_col_heads)
            csv << sub_vals
        end
    end
  end
  def get_hla
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        hla_col_heads = Hla.column_names.reject{ |cn| ["id", "subject_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(hla_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        hlas = Hla.where(subject_id:subjects_ids)
        csv << full_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*["hlac19_id", "origin_identifier"])
            hla_vals = Hla.find_by(subject_id:sid) ? Hla.find_by(subject_id:sid).attributes.values_at(*hla_col_heads) : nil
            row = (hla_vals.nil?) ? sub_vals : sub_vals.concat(hla_vals)
            csv << row
        end
    end
  end
  def get_kir
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        kir_col_heads = Kir.column_names.reject{ |cn| ["id", "subject_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(kir_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        kirs = Kir.where(subject_id:subjects_ids)
        csv << full_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*["hlac19_id", "origin_identifier"])
            kir_vals = Kir.find_by(subject_id:sid) ? Kir.find_by(subject_id:sid).attributes.values_at(*kir_col_heads) : nil
            row = (kir_vals.nil?) ? sub_vals : sub_vals.concat(kir_vals)
            csv << row
        end
    end
  end
  def get_stats
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        stat_col_heads = Imputationstat.column_names.reject{ |cn| ["id", "hla_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(stat_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        hlas = Hla.where(subject_id:subjects_ids)
        csv << full_col_heads
        hlas.each do |h|
            sub_vals = h.subject.attributes.values_at(*["hlac19_id", "origin_identifier"])
            stat_vals = h.imputationstat.attributes.values_at(*stat_col_heads)
            row = sub_vals.concat(stat_vals)
            csv << row
        end
    end
  end
  def get_comorbidities
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        comorb_col_heads = Comorbidity.column_names.reject{ |cn| ["id", "subject_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(comorb_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        csv << full_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*["hlac19_id", "origin_identifier"])
            comorb_vals = Comorbidity.find_by(subject_id:sid) ? Comorbidity.find_by(subject_id:sid).attributes.values_at(*comorb_col_heads) : nil
            row = (comorb_vals.nil?) ? sub_vals : sub_vals.concat(comorb_vals)
            csv << row
        end
    end
  end  
  def get_symptoms
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        c19_col_heads = C19Symptom.column_names.reject{ |cn| ["id", "subject_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(c19_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        csv << full_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*["hlac19_id", "origin_identifier"])
            c19_vals = C19Symptom.find_by(subject_id:sid) ? C19Symptom.find_by(subject_id:sid).attributes.values_at(*c19_col_heads) : nil
            row = (c19_vals.nil?) ? sub_vals : sub_vals.concat(c19_vals)
            csv << row
        end
    end
  end
  def get_hospitalizations
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        hosp_col_heads = Hospitalization.column_names.reject{ |cn| ["id", "subject_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(hosp_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        csv << full_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*["hlac19_id", "origin_identifier"])
            hosp_vals = Hospitalization.find_by(subject_id:sid) ? Hospitalization.find_by(subject_id:sid).attributes.values_at(*hosp_col_heads) :nil
            row = (hosp_vals.nil?) ? sub_vals : sub_vals.concat(hosp_vals)
            csv << row
        end
    end
  end
  def get_lab_tests
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        lb_col_heads = LabTest.column_names.reject{ |cn| ["id", "subject_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(lb_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        csv << full_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*["hlac19_id", "origin_identifier"])
            lb_vals = LabTest.find_by(subject_id:sid) ? LabTest.find_by(subject_id:sid).attributes.values_at(*lb_col_heads) : nil
            row = (lb_vals.nil?) ? sub_vals : sub_vals.concat(lb_vals)
            csv << row
        end
    end
  end
  def get_risk_factors
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        rf_col_heads = RiskFactor.column_names.reject{ |cn| ["id", "subject_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(rf_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        csv << full_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*["hlac19_id", "origin_identifier"])
            rf_vals = RiskFactor.find_by(subject_id:sid) ? RiskFactor.find_by(subject_id:sid).attributes.values_at(*rf_col_heads) : nil
            row = (rf_vals.nil?) ? sub_vals : sub_vals.concat(rf_vals)
            csv << row
        end
    end
  end
  def get_treatments
    CSV.generate do |csv|
        sub_col_heads = ["hlac19_id", "origin_identifier"]
        tmt_col_heads = Treatment.column_names.reject{ |cn| ["id", "subject_id", "created_at", "updated_at"].include? cn }.map{ |cn| cn.to_s }
        full_col_heads = sub_col_heads.concat(tmt_col_heads)
        subjects_ids = self.subjects.pluck(:id)
        tmts = Treatment.where(subject_id:subjects_ids)
        csv << full_col_heads
        subjects_ids.each do |sid|
            sub_vals = Subject.find(sid).attributes.values_at(*["hlac19_id", "origin_identifier"])
            tmt_vals = Treatment.find_by(subject_id:sid) ? Treatment.find_by(subject_id:sid).attributes.values_at(*tmt_col_heads) : nil
            row = (tmt_vals.nil?) ? sub_vals : sub_vals.concat(tmt_vals)
            csv << row
        end
    end
  end


end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
    def index
        authenticate_user!
        @user_owned_projects = current_user.projects
        user_approved_access = current_user.approved_access
        @projects = current_user.projects.concat(Project.where(id:current_user.approved_access))
        @current_project = (params[:project_id].nil?) ? current_user.projects.first : current_user.projects.find(params[:project_id])
        @manage_projects = Project.where(id: current_user.grant_project_access_to)
    end


end

app/views/project/partials/_c19_symptoms_datatable.html.erb
<div class="tab-pane container" id="c19-symptoms-table-pane">
    <table id="c19-symptoms-datatable" class="table table-bordered" data-source="<%= datatables_c19_symptoms_path(format: :json, :project_id => @current_project.id) %>">
        <thead>
            <tr>
                <th>ID</th>
                <th>HLAC19_ID</th>
                <th>Origin Identifier</th> 
                <th>Dry Cough</th>
                <th>Mucus Cough</th>
                <th>Days Cough</th>
                <th>Difficulty Breathing</th>
                <th>Fever</th>
                <th>Highest Temp</th>
                <th>Days Fever</th>
                <th>Fatigue</th>
                <th>Pain Chest/Heart</th>
                <th>Pain Back</th>
                <th>Runny Nose</th>
                <th>Sore Throat</th>
                <th>Loss Taste/Smell</th>
                <th>Diarrhea</th>
                <th>Nausea</th>
                <th>Other Symptoms</th>
                <th>C19 Test Result Pos</th>
                <th>Type C19 Test</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/project/partials/_comorbidity_datatable.html.erb
<div class="tab-pane container" id="comorbidity-table-pane">
    <table id="comorbidity-datatable" class="table table-bordered" data-source="<%= datatables_comorbidity_path(format: :json, :project_id => @current_project.id) %>">
        <thead>
            <tr>
                <th>ID</th>
                <th>HLAC19_ID</th>
                <th>Origin Identifier</th> 
                <th>HIV</th>
                <th>CD4 cell count</th>
                <th>HIV load</th>
                <th>Immunocompromised</th>
                <th>Organ transplant</th>
                <th>Organ transplant type</th>
                <th>Bone marrow transplant</th>
                <th>Autoimmune rheum disease</th>
                <th>Diabetes type 1</th>
                <th>Diabetes type 2</th>
                <th>Asthma</th>
                <th>COPD</th>
                <th>Cycstic fib</th>
                <th>Liver disease</th>
                <th>Gallbladder disease</th>
                <th>Pancreas disease</th>
                <th>Angio coronary intervention</th>
                <th>Artery bypass</th>
                <th>Cong heart failure</th>
                <th>Hypertension</th>
                <th>Infarction type 1</th>
                <th>Infarction type 2</th>
                <th>Peri vascular dis</th>
                <th>Stroke</th>
                <th>Arythmia</th>
                <th>Dementia</th>
                <th>Neur disease</th>
                <th>Leukemia</th>
                <th>Lymphoma</th>
                <th>Malignant solid tumor</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/project/partials/_download.html.erb
<br>
<div class="row justify-content-md-center">
    <h3>Download Data from your projects</h3>
</div>
<div class="row justify-content-md-center">
    <!-- if user has more than one project they can access, include a drop down select control to choose another project, otherwise leave select control out -->
    <% if @projects.count == 1 %>
        <div class="col-12">
            <h1><%= @current_project.name%></h1>
        </div>
    <% else %>
        <div class="col-10">
            <h1><%= @current_project.name%></h1>
        </div>
        <div class="col-2">
            <%= select_tag "projects", options_for_select(@projects.collect{ |p| [p.name, p.id]}, :selected => @current_project.id), :class => "form-control", :id => "project-select-control" %>
        </div>
    <% end %>
</div>
<br>
<div class="row justify-content-md-center">
    <div class="col-12">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#subjects-table-pane">Subjects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#c19-symptoms-table-pane">COVID-19 Symptoms</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#hla-table-pane">HLA</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#kir-table-pane">KIR</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#comorbidity-table-pane">Comorbidity</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#hospitalization-table-pane">Hospitalization</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#riskfactor-table-pane">Risk Factor</a>
            </li>
            <%# <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#labtest-table-pane">Lab Test</a>
            </li> %>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#treatment-table-pane">Treatment</a>
            </li>
        </ul>
    </div>
</div>
<div class="row justify-content-md-center">
    <div class="col-12">
        <div class="tab-content data-table-container">
            <%= render 'project/partials/subjects_datatable' %>
            <%= render 'project/partials/c19_symptoms_datatable' %>
            <%= render 'project/partials/hla_datatable' %>
            <%= render 'project/partials/kir_datatable' %>
            <%= render 'project/partials/comorbidity_datatable' %>
            <%= render 'project/partials/hospitalization_datatable' %>
            <%= render 'project/partials/riskfactor_datatable' %>
            <%# <%= render 'project/partials/labtest_datatable' %> 
            <%= render 'project/partials/treatment_datatable' %>
        </div>
    </div>
</div>
<br>

app/views/project/partials/_hla_datatable.html.erb
<div class="tab-pane container" id="hla-table-pane">
    <table id="hla-datatable" class="table table-bordered" data-source="<%= datatables_hla_path(format: :json, :project_id => @current_project.id) %>">
        <thead>
            <tr>
                <th>ID</th>
                <th>HLAC19_ID</th>
                <th>Origin Identifier</th> 
                <th>DRB1_1</th>
                <th>DRB1_2</th>
                <th>DQB1_1</th>
                <th>DQB1_2</th>
                <th>DPB1_1</th>
                <th>DPB1_2</th>
                <th>A_1</th>
                <th>A_2</th>
                <th>B_1</th>
                <th>B_2</th>
                <th>C_1</th>
                <th>C_2</th>
                <th>DPA1_1</th>
                <th>DPA1_2</th>
                <th>DQA1_1</th>
                <th>DQA1_2</th>
                <th>DRBo_1</th>
                <th>DRBo_2</th>
                <th>DRB345_1</th>
                <th>DRB345_2</th>
                <th>Reference DB</th>
                <th>Reference DB Version</th>
                <th>Typing Method</th>
                <th>Typing Method Version</th>
                <th>GL String</th>
                <th>Novel Polymorphisms</th>
                <th>Pop.</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/project/partials/_hospitalization_datatable.html.erb
<div class="tab-pane container" id="hospitalization-table-pane">
    <table id="hospitalization-datatable" class="table table-bordered" data-source="<%= datatables_hospitalization_path(format: :json, :project_id => @current_project.id) %>">
        <thead>
            <tr>
                <th>ID</th>
                <th>HLAC19_ID</th>
                <th>Origin Identifier</th> 
                <th>Icu admit</th>
                <th>Icu duration days</th>
                <th>Reason hosp ended</th>
                <th>Septic shock</th>
                <th>Days after c19 septic shock</th>
                <th>Organ failure</th>
                <th>resp failure</th>
                <th>resp rate intake</th>
                <th>resp breath per min</th>
                <th>blood o2 sat</th>
                <th>highest resp support</th>
                <th>days ventilator</th>
                <th>pa02 min</th>
                <th>fio2 max</th>
                <th>lung infiltrates</th>
                <th>pneumonia</th>
                <th>pneumonia days after c19 symptoms</th>
                <th>ef echo</th>
                <th>hepatitis</th>
                <th>pancreatitis</th>
                <th>pleural effusion</th>
                <th>acute kidney failure</th>
                <th>acute kidney chronic</th>
                <th>ascites</th>
                <th>dyspnea</th>
                <th>hospitalization duration days</th>
                <th>hospitalization admit</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/project/partials/_kir_datatable.html.erb
<div class="tab-pane container" id="kir-table-pane">
    <table id="kir-datatable" class="table table-bordered" data-source="<%= datatables_kir_path(format: :json, :project_id => @current_project.id) %>">
        <thead>
            <tr>
                <th>ID</th>
                <th>HLAC19 ID</th>
                <th>Origin Identifier</th> 
                <th>k2dl4_1</th>
                <th>k2dl4_2</th>
                <th>k2dl23_1</th>
                <th>k2dl23_2</th>
                <th>k3dl1s1_1</th>
                <th>k3dl1s1_2</th>
                <th>k3dl2_1</th>
                <th>k3dl2_2</th>
                <th>k3dl3_1</th>
                <th>k3dl3_2</th>
                <th>k2dl1_1</th>
                <th>k2dl1_2</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/project/partials/_labtest_datatable.html.erb
<div class="tab-pane container" id="labtest-table-pane">
    <table id="labtest-datatable" class="table table-bordered" data-project="<%= @current_project.id %>" data-source="<%= datatables_labtest_path %>">
        <thead>
            <tr>
                <th>ID</th>
                <th>HLAC19 ID</th>
                <th>Origin Identifier</th> 
                <th>Blood type</th>
                <th>Rh factor</th>
                <th>WBC</th>
                <th>Lymphocytes</th>
                <th>Neutrophils</th>
                <th>Monocytes</th>
                <th>Eosinophils</th>
                <th>Basophils</th>
                <th>CRP</th>
                <th>Trop i</th>
                <th>Trop t</th>
                <th>BNP</th>
                <th>IDH</th>
                <th>AST</th>
                <th>ALT</th>
                <th>Bilirubin</th>
                <th>GGT</th>
                <th>ALP</th>
                <th>D dimer</th>
                <th>Il6</th>
                <th>Tumor necrosis factor</th>
                <th>Serum femtin</th>
                <th>Hba1c</th>
                <th>Cholesterol</th>
                <th>Triglycerides</th>
                <th>HDL</th>
                <th>LDL</th>
                <th>Ace</th>
                <th>Ace2r</th>
                <th>Hemoglobin</th>
                <th>Amylase</th>
                <th>Lipase</th>
                <th>Urea</th>
                <th>Creatinine</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/project/partials/_manage.html.erb
 <br>
 <div class="row justify-content-md-center">
    <h3>Manage access to data from your projects</h3>
    <br>
    <h6>A checked box indicates that user has access to, and may download, data from your project. To remove access, uncheck a checked box.</h6>
</div>
<br>
<div class="row justify-content-md-center">
    <div class="col-md-10">
        <table class="table">
            <thead>
                <th>User email</th>
                <% current_user.projects.each do |p| %>
                    <th><%= p.name %></th>
                <% end %>
            </thead>
            <tbody>
                <% User.where(approved:true).reject{ |u| u.id == current_user.id }.each do |u| %>
                    <tr>
                        <td><%= u.email %></td>
                        <% @manage_projects.each do |p| %>
                            <td>
                                <input type='checkbox' class="user-list" data-userid="<%= u.id %>" data-projectid="<%= p.id %>" data-appstatus = <%= (u.approved_access.include? p.id ) ? "yes" : "no" %> ><span id="status-<%=p.id%>">
                            </td>
                        <% end %>
                    </tr>
                <% end %>
            <tbody>
        </table>
    </div>
</div>

app/views/project/partials/_riskfactor_datatable.html.erb
<div class="tab-pane container" id="riskfactor-table-pane">
    <table id="riskfactor-datatable" class="table table-bordered" data-source="<%= datatables_riskfactor_path(format: :json, :project_id => @current_project.id) %>">
        <thead>
            <tr>
                <th>ID</th>
                <th>HLAC19 ID</th>
                <th>Origin Identifier</th> 
                <th>Smoke freq</th>
                <th>Alcohol freq</th>
                <th>Substances freq</th>
                <th>Smoke</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/project/partials/_subjects_datatable.html.erb
<div class="tab-pane container active" id="subjects-table-pane">
    <table id="subjects-datatable" class="table table-bordered" data-source="<%= datatables_subjects_path(format: :json, :project_id => @current_project.id) %>">
        <thead>
            <tr>
                <th>HLAC19 ID</th>
                <th>Origin ID</th>
                <th>Sex</th>
                <th>Gender</th>
                <th>Education</th>
                <th>Age</th>
                <th>Ethnicity</th>
                <th>Pregnant</th>
                <th>Ancestry</th>
                <th>Height (cm)</th>
                <th>Weight (kg)</th>
                <th>Race</th>
                <th>Country of Residence</th>
                <th>Vaccinated</th>
                <th>Vaccine Type</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/project/partials/_treatment_datatable.html.erb
<div class="tab-pane container" id="treatment-table-pane">
    <table id="treatment-datatable" class="table table-bordered" data-source="<%= datatables_treatment_path(format: :json, :project_id => @current_project.id) %>">
        <thead>
            <tr>
                <th>ID</th>
                <th>HLAC19 ID</th>
                <th>Origin Identifier</th> 
                <th>Ace inhib</th>
                <th>Angio blocker</th>
                <th>Antibiotics</th>
                <th>Antiviral med</th>
                <th>Allergy med</th>
                <th>Androgen med</th>
                <th>Asthma med</th>
                <th>Immunosuppressor light</th>
                <th>Immunosuppressor strong</th>
                <th>Biologics mabs</th>
                <th>NSAID</th>
                <th>Antipytetics</th>
                <th>Blood thinner</th>
                <th>Vitamin D med</th>
                <th>Vitamin C med</th>
                <th>Med UCDA</th>
                <th>Treatment duration days</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>