config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => "users/registrations"}
  root 'home#index'

  get 'home/auth'
  get 'home/project'
  get 'home/subjects_csv'
  get 'home/hla_csv'
  get 'home/kir_csv'
  get 'home/c19_symptoms_csv'
  get 'home/comorbidities_csv'
  get 'home/hospitalizations_csv'
  get 'home/lab_tests_csv'
  get 'home/risk_factors_csv'
  get 'home/treatments_csv'
  get 'home/stats_csv'
  get 'home/age_data'
  get 'home/sex_data'
  get 'home/contributor_table_data'
  get 'home/allele_freq_data'
  get 'home/download_manual'
  get 'home/new_account_approval'
  post 'home/new_account_approval_handler'
  get 'project/index/:project_id', to: 'project#index', as: 'project_index'
  get 'upload/index'
  get 'upload/get_report'
  patch 'upload/import_data'
  patch 'upload/store'
  get 'upload/download_template'
  get 'upload/download_dictionary'
  get 'datatables/subjects'
  get 'datatables/c19_symptoms'
  get 'datatables/hla'
  get 'datatables/kir'
  get 'datatables/comorbidity'
  get 'datatables/hospitalization'
  post 'datatables/labtest'
  get 'datatables/riskfactor'
  get 'datatables/treatment'
  post 'query/data'
  post 'query/import_hla'
  post 'query/hibag_preflight'
  post 'query/user_key'
  post 'home/approve_users'
  get '*unmatched', to: 'error#error_404', via: :all, as: 'error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        test_pids = Project.where(is_test:true).pluck(:id)
        @subjects_n = Subject.where.not(project_id:test_pids).count
        subject_ids = Project.where.not(id:test_pids).map{ |p| p.subjects.pluck(:id) }.flatten
        @all_hlas_n = Hla.where(subject_id:subject_ids).count
        @hla_genes = Hla.column_names.reject{ |cn| ["id", "subject_id", "updated_at", "created_at", "reference_database", "reference_database_version", "typing_method_name", "typing_method_version", "gl_string", "novel_polymorphisms", "pop", "imputed_using_hlacovid_platform", "drbo_1", "drbo_2", "drb345_1", "drb345_2"].include? cn }
        @hla_genes = @hla_genes.map{ |g| g.split("_").first}.uniq
        @imputed_hlas_n = Hla.where(subject_id:subject_ids).where(imputed_using_hlacovid_platform:true).count
        if current_user
            @user = current_user
        else
            @user = User.new
        end
    end
    def auth
        unless current_user
            @user = User.new
        end
    end
    def account
    end
    def access
        @projects = current_user.projects
    end
    def project
        # 02-26-2021 removed a broken method to show projects that a user doesn't own, but has access to. 
        # This will now only serve current_user's projects.
        # Will add a method to serve up other projects if there is a need for it
        authenticate_user!
        @user_owned_projects = current_user.projects
    end
    def approve_users
        @user = User.find(approved_users_params[:user].to_i)
        approved_list = approved_users_params[:approved] == "true" ? @user.approved_access.concat([approved_users_params[:project].to_i]) : @user.approved_access - [approved_users_params[:project].to_i]
        @user.update(approved_access:approved_list)
        status = (@user.approved_access.include?(approved_users_params[:project].to_i)) ? "access approved" : "no access"
        respond_to do |format|
            format.json { render json: {"user_status": status }, status: :ok}
        end
    end
    def new_account_approval
        unless current_user && (current_user.can_approve_new_user || current_user.admin?)
            redirect_to root_path
        end
        @new_accounts = User.where(approved:false).where(suppress_from_approval_view:false)

    end
    def new_account_approval_handler
        @user = User.find_by(email:account_approval_params[:email])
        if @user && @user.update(account_approval_params)
            @status = "OK"
        else
            @status = "ERROR"
        end
        respond_to do |format|
            format.json { render json: {"accepted": @status }, status: :accepted }
        end
    end
    def subjects_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_subjects, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_subjects.csv" }
        end
    end
    def hla_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_hla, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_HLA.csv" }
        end
    end
    def kir_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_kir, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_KIR.csv" }
        end
    end
    def stats_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_stats, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_imputation_stats.csv" }
        end
    end
    def comorbidities_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_comorbidities, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_comorbidities.csv" }
        end
    end
    def c19_symptoms_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_symptoms, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_COVID-19_symptoms.csv" }
        end
    end
    def hospitalizations_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_hospitalizations, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_hospitalizations.csv" }
        end
    end
    def lab_tests_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_lab_tests, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_lab_tests.csv" }
        end
    end
    def risk_factors_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_risk_factors, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_risk_factors.csv" }
        end
    end
    def treatments_csv
        @project = Project.find(params[:id])
        respond_to do |format|
            format.csv { send_data @project.get_treatments, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@project.name}_treatments.csv" }
        end
    end

    def age_data
        results = ActiveRecord::Base.connection.execute("select age, count(s.id) from subjects s join projects p on s.project_id = p.id where p.is_test = false group by s.age")
        respond_to do |format|
            format.html
            format.json { render json: { :data => results }, status: :ok }
        end
    end
    def sex_data
        puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        results = ActiveRecord::Base.connection.execute("select sex, count(s.id) from subjects s join projects p on s.project_id = p.id where p.is_test = false and sex in ('M','F') group by s.sex")
        puts results.to_json
        respond_to do |format|
            format.html
            format.json { render json: { :data => results }, status: :ok }
        end
    end
    def allele_freq_data
        gp1 = "#{allele_freq_data_params[:gene]}_1"
        gp2 = "#{allele_freq_data_params[:gene]}_2"
        query_1 = "SELECT h.#{gp1} as allele, count(h.id) as n from hlas h join subjects s on h.subject_id = s.id where s.project_id in (1, 10, 11, 17, 19, 22) group by h.#{gp1}"
        query_2 = "SELECT h.#{gp2} as allele, count(h.id) as n from hlas h join subjects s on h.subject_id = s.id where s.project_id in (1, 10, 11, 17, 19, 22) group by h.#{gp2}"
        result_1 = ActiveRecord::Base.connection.exec_query(query_1)
        result_2 = ActiveRecord::Base.connection.exec_query(query_2)

        freq_hash = {}
        # AGGREGATE THE TOTALS FROM THE SINGLE GENE COUNT QUERIES INTO ONE HASH
        [result_1, result_2].each do |r|
            r.each do |h|
                gls = h["allele"]
                # NORMALIZE ALLELE STRINGS: STRIP OFF GENE PREFIX, SHORTEN AMBIGUOUS CALLS, CONDENSE GL STRINGS TO 2 FIELDS, AND INSERT LEADING ZEROES WHERE NEEDED
                unless gls.nil?
                    gls = (gls.include? "*") ? gls.split("*")[1] : gls # STRIP GENE NAMES
                    gls = (gls.include? "/") ? gls.split("/")[0] : gls # SHORTEN AMBIGUOUS CALLS
                    gls = (gls.scan(':').size > 1) ? "#{gls.split(':').first}:#{gls.split(':').second}" : gls # CONDENSE GL STRINGS TO TWO FIELDS 
                    gls = (/^\d{1}:/.match(gls)) ? "#{gls.split(':').first.rjust(2, '0')}:#{gls.split(':').second}" : gls # ADD LEADING ZEROES IF FIRST FIELD IS ONLY ONE DIGIT
                    gls = (/^\d{1}$/.match(gls)) ? "#{gls.rjust(2, '0')}" : gls
                    # BEFORE ADDING TO THE FREQUENCY HASH CHECK TO SEE THAT THE GENE NAME ISN'T 'NA' OR 'INSERTION' OR ANYTHING THAT ISN'T A VALID GL STRING. IF IT IS, SKIP TO THE NEXT ALLELE
                    unless /^[0-9]/.match? gls.to_s
                        next
                    end
                    if freq_hash[gls]
                        freq_hash[gls] += h["n"]
                    else
                        freq_hash[gls] = h["n"]
                    end
                end
            end
        end
        # DETERMINE EACH GENOTYPE'S FREQUENCY BY DIVIDING EACH GENOTYPE'S COUNT BY 2X THE TOTAL HLA (BY THE NUMBER OF NON-NULL VALID GENOTYPES FOR THAT GENE)
        #gp1_count = ActiveRecord::Base.connection.execute("SELECT count(h.id) from hlas h join subjects s on h.subject_id = s.id where h.#{gp1} is not null and h.#{gp1} <> 'NA' and h.#{gp1} <> 'insertion/deletion' and s.project_id in (1, 10, 11, 17, 19, 22)")
        gp1_count = ActiveRecord::Base.connection.execute("SELECT count(h.id) from projects p join subjects s on p.id = s.project_id join hlas h on h.subject_id = s.id where h.#{gp1} is not null and h.#{gp1} <> 'NA' and h.#{gp1} <> 'insertion/deletion' and p.is_test = false")
        #gp2_count = ActiveRecord::Base.connection.execute("SELECT count(h.id) from hlas h join subjects s on h.subject_id = s.id where h.#{gp2} is not null and h.#{gp2} <> 'NA' and h.#{gp2} <> 'insertion/deletion' and project_id in (1, 10, 11, 17, 19, 22)")
        gp2_count = ActiveRecord::Base.connection.execute("SELECT count(h.id) from projects p join subjects s on p.id = s.project_id join hlas h on h.subject_id = s.id where h.#{gp2} is not null and h.#{gp2} <> 'NA' and h.#{gp2} <> 'insertion/deletion' and p.is_test = false")

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/auth.html.erb
<div class="container">
    <div class="row justify-content-md-center" style="margin-top:50px;">
        <div class="col-6">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#log-in-form">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#registration-form">Register Account</a>
                </li>
            </ul>

                <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane container active" id="log-in-form">
                <br />
                    <h2>Log in</h2>
                    <%= form_for(@user, url: session_path(@user)) do |f| %>
                        <div class="row form-group" style="margin-left:1px;margin-right:1px;">
                            <%= f.label :email, :class => "col-4 col-form-label"  %><br />
                            <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => "form-control", :required => true %>
                        </div>

                        <div class="row form-group" style="margin-left:1px;margin-right:1px;">
                            <%= f.label :password, :class => "col-4 col-form-label" %><br />
                            <%= f.password_field :password, autocomplete: "password", :class => "form-control", :required => true %>
                        </div>

                        <div class="row justify-content-md-center" style="margin-bottom:15px;"> 
                            <div class="actions">
                                <%= f.submit "Log in", :class => "btn btn-primary" %>
                            </div>
                        </div>

                          <div class="row justify-content-md-center">
                            <div class="">
                                <%= link_to "Forgot your password?", new_password_path(@user) %>
                            </div>
                        </div>
                    <% end %>
                </div>
                <div class="tab-pane container fade" id="registration-form">
                <br />
                    <h2>Register New Account</h2>
                    
                    <%= form_for(@user, url: registration_path(@user)) do |f| %>
                        <div class="row form-group" style="margin-left:1px; margin-right:1px;">
                            <%= f.label :firstname, "First name", :class => "col-4 col-form-label" %><br />
                            <%= f.text_field :firstname, :class => "form-control", :required => true %>
                        </div>

                        <div class="row form-group" style="margin-left:1px; margin-right:1px;">
                            <%= f.label :lastname, "Last name", :class => "col-4 col-form-label" %><br />
                            <%= f.text_field :lastname, :class => "form-control", :required => true %>
                        </div>

                        <div class="row form-group" style="margin-left:1px;margin-right:1px;">
                            <%= f.label :email, :class => "col-4 col-form-label" %><br />
                            <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => "form-control", :required => true %>
                        </div>

                        <div class="row form-group" style="margin-left:1px;margin-right:1px;">
                            <%= f.label :affiliation, "Institutional Affiliation", :class => "col-10 col-form-label" %><br />
                            <%= f.text_field :affiliation, :class => "form-control", :required => true %>
                        </div>

                        <div class="row form-group" style="margin-left:1px;margin-right:1px;">
                            <%= f.label :password, :class => "col-4 col-form-label" %>
                            <% if @minimum_password_length %>
                            <em>(<%= @minimum_password_length %> characters minimum)</em>
                            <% end %><br />
                            <%= f.password_field :password, autocomplete: "new-password", :class => "form-control", :required => true %>
                        </div>

                        <div class="row form-group" style="margin-left:1px;margin-right:1px;">
                            <%= f.label :password_confirmation, :class => "col-10 col-form-label" %><br />
                            <%= f.password_field :password_confirmation, autocomplete: "new-password", :class => "form-control" %>
                        </div>
                        <div class="row form-group" style="margin-left:20px;margin-right:1px;">
                            <%= f.check_box :email_opt_in, :class => "form-check-input", :required => true %>
                            <%= f.label :email_opt_in, "The HLA | COVID19 database portal uses email to contact users to perform site functions. By clicking here you agree to receive emails from the HLA | COVID19 database portal (required for registration).", :class => "form-check-label"%>
                        </div>
                        <div class="row justify-content-md-center"  style="margin-left:1px;margin-right:1px;"> 
                        <p style="font-size:10pt;"> <input type="checkbox" id="reg-chkbox"> I understand new account applications are reviewed and subject to approval of the HLA-COVID19 governing body.
                         Approved users shall be notified by email. I acknowledge my account will be inactive until I am otherwise notified. </p>
                        </div>
                        <div class="row justify-content-md-center" style="margin-bottom:15px;" >
                          <div class="field">
                            <%= recaptcha_tags %>
                          </div>
                        </div>
                        <div class="row justify-content-md-center" style="margin-bottom:15px;"> 
                            <div class="actions">
                                <%= f.submit "Register", :class => "btn btn-primary", :id => "new_registration_submit", :disabled => true %>
                            </div>
                        </div>

                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid main-view" >
    <div class="row justify-content-md-center" style="margin-top:40px;margin-bottom:50px;">
        <div class="col-10">
            <h2>HLA | COVID-19 Database portal</h2>
            <br>
            <p>From here, users may register for an account, view summary statistics, upload data and manage access to it, and request access to the consortium's online
            HLA imputation tool and RStudio Server platform.<p>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-3">
            <h4>Data contributors</h4>
            <br>
            <div id="contributor-chart"></div>
        </div>
        <div class="col-md-3">
            <div id="sex-chart"></div>
        </div>
        <div class="col-md-3">
            <div id="age-chart"></div>
        </div>
        <div class="col-md-3">
            <div id="n-chart-box">
                <div id="n-chart-inner">
                    <div class="n-chart-label-box">
                        <h6 class="n-chart-label">Subjects</h6>
                    </div>
                    <div id="n-chart-subjects-box">
                        <h1 class="n-chart-value text-center"><%= @subjects_n %></h1>
                    </div>
                    <hr>
                    <div class="n-chart-label-box">
                        <h6 class="n-chart-label">HLA</h6>
                    </div>
                    <div id="n-chart-hlas-box">                   
                        <div id="n-chart-imputed-hlas-box">
                            <div class="n-chart-value-box">
                                <h1 class="n-chart-value text-center"><%= @all_hlas_n %></h1>
                            </div>
                            <div class="n-chart-label-box">
                                <h6 class="n-chart-label text-center"></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row justify-content-md-center">
        <h4>Allele Frequencies</h4>
    </div>
    <% @hla_genes.each_with_index do |g, idx| %>
        <% if idx == 0 || idx == 4 %>
            <div class="row justify-content-md-center">
                <div class="col-md-3" id="<%= g %>-chart-container">
                    <div class="allele-freq-chart" data-gene="<%= @hla_genes[idx] %>" id="<%= @hla_genes[idx] %>-chart"></div>
                </div>
                <div class="col-md-3" id="<%= g %>-chart-container">
                    <div class="allele-freq-chart" data-gene="<%= @hla_genes[idx + 1] %>" id="<%= @hla_genes[idx + 1] %>-chart"></div>
                </div>
                <div class="col-md-3" id="<%= g %>-chart-container">
                    <div class="allele-freq-chart" data-gene="<%= @hla_genes[idx + 2] %>" id="<%= @hla_genes[idx + 2] %>-chart"></div>
                </div>
                <div class="col-md-3" id="<%= g %>-chart-container">
                    <div class="allele-freq-chart" data-gene="<%= @hla_genes[idx + 3] %>" id="<%= @hla_genes[idx + 3] %>-chart"></div>
                </div>
            </div>
        <% else %>
            <% next %>
        <% end %>
    <% end %>

</div>

app/views/home/new_account_approval.html.erb
<div class="container">
    <div class="row justify-content-md-center">
        <h1>User accounts awaiting approval</h1>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-10">
            <table class="table table-bordered table-striped" style="width:100%">
                <tr>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Email</th>
                    <th>Affiliation</th>
                    <th>Registered</th>
                    <th>Approve</th>
                    <th>Remove from Consideration</th>
                <% @new_accounts.each_with_index do |na, idx| %>
                    <tr data-index=<%= idx %>>
                        <td><%= na.firstname %></td>
                        <td><%= na.lastname %></td>
                        <td><%= na.email %></td>
                        <td><%= na.affiliation %></td>
                        <td><%= na.created_at.strftime("%m-%d-%Y") %>
                        <td><button data-index=<%= idx %> data-email=<%= na.email %> class="approve-new-user-button btn btn-primary">Approve</button></td>
                        <td><button data-index=<%= idx %> data-email=<%= na.email %> class="remove-new-user-button btn btn-primary">Remove</button></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>

</div>

app/views/home/project.html.erb
<div class="container-fluid">
    <br>
    <div class="row justify-content-md-center">
        <div class="col-md-10">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#download">Download Data</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#manage">Manage Access</a>
                </li>
            </ul>
        </div>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane container active" id="download"><%= render 'home/partials/download' %></div>
            <div class="tab-pane container fade" id="manage"><%= render 'home/partials/manage' %></div>
        </div>
    </div>
</div>