config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => "users/registrations"}
  root 'home#index'

  get 'home/auth'
  get 'home/project'
  get 'home/subjects_csv'
  get 'home/hla_csv'
  get 'home/kir_csv'
  get 'home/c19_symptoms_csv'
  get 'home/comorbidities_csv'
  get 'home/hospitalizations_csv'
  get 'home/lab_tests_csv'
  get 'home/risk_factors_csv'
  get 'home/treatments_csv'
  get 'home/stats_csv'
  get 'home/age_data'
  get 'home/sex_data'
  get 'home/contributor_table_data'
  get 'home/allele_freq_data'
  get 'home/download_manual'
  get 'home/new_account_approval'
  post 'home/new_account_approval_handler'
  get 'project/index/:project_id', to: 'project#index', as: 'project_index'
  get 'upload/index'
  get 'upload/get_report'
  patch 'upload/import_data'
  patch 'upload/store'
  get 'upload/download_template'
  get 'upload/download_dictionary'
  get 'datatables/subjects'
  get 'datatables/c19_symptoms'
  get 'datatables/hla'
  get 'datatables/kir'
  get 'datatables/comorbidity'
  get 'datatables/hospitalization'
  post 'datatables/labtest'
  get 'datatables/riskfactor'
  get 'datatables/treatment'
  post 'query/data'
  post 'query/import_hla'
  post 'query/hibag_preflight'
  post 'query/user_key'
  post 'home/approve_users'
  get '*unmatched', to: 'error#error_404', via: :all, as: 'error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-bottom:1px solid lightgrey;">

  <%= link_to image_tag("logo_captioned2.png", width:175), root_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <%= link_to "HLACOVID19.org", "http://hlacovid19.org", :class => "nav-link", target: :blank %>
        </li>
        <li class="nav-item">
          <%= link_to "Download Database Manual", home_download_manual_path, :class => "nav-link", target: :blank %>
        </li>
        <% if current_user && (current_user.admin? || current_user.can_approve_new_user) %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              Administration
            </a>
            <div class="dropdown-menu">
              <% if current_user.admin? %>
                <%= link_to "Rails Admin", rails_admin_path, :class => "nav-link", target: :blank %>
              <% end %>
              <%= link_to "New Users", home_new_account_approval_path, :class => "nav-link", target: :blank %>
            </div>
          </li>
        <% end %>
        <% if !current_user %>
            <li class="nav-item"><%= link_to "Log In / Register Account", home_auth_path, :class => "nav-link"%></li>
        <% else %>
            <% if current_user.can_upload == true && current_user.projects.count > 0 %>
                <li class="nav-item"><%= link_to "File Uploads", upload_index_path, :class => "nav-link"%></li>
            <% end %>
            <% if Rails.env == "production" && current_user.rstudio == true %>
                <li class="nav-item"><%= link_to "RStudio server", "https://database-hlacovid19.org/rstudio", target: :_blank, :class => "nav-link" %>
            <% end %>
            <% if (current_user.project_owner && current_user.projects.count > 0) %>
                <li class="nav-item"><%= link_to "Project Data" , project_index_path(current_user.projects.first.id), :class => "nav-link"%></li>
            <% elsif !current_user.approved_access.empty? %>
                <li class="nav-item"><%= link_to "Project Data" , project_index_path(current_user.approved_access.first), :class => "nav-link"%></li>
            <% end %>
            <li class="nav-item"><%= link_to "My Account", edit_user_registration_path, :class => "nav-link"%></li>
            <li class="nav-item"><%= button_to("Logout", destroy_user_session_path, method: :delete, :class => "nav-link")%></li>
        <% end %>
      </li>

    </ul>
  </div>
</nav>